V7 (#510)
* WIP with api root page

* include version swtich at the footer

* create all the pages

* fix menu and include version select

* fix api page link

* register function ready

* include example for register

* include extra options for unregister to keep state (#511)

* working watch api

* update all v7 examples

* fix some of the missing ones

* include aria-label for api gallery page

* useForm API skeleton in place

* remove api page and include error message in side form state

* include useFormContext

* API page port skeleton complete

* side bar active state

* include version toggler

* update home page

* include version toggle at gallery

* polished useForm page

* clean up useform data

* builder to support v6 and v7

* include useFormState page

* clean up useForm API doc

* update controller and useController

* update useWatch

* include redirect

* fix url path

* update doc for useFieldArray

* fix builder

* clean up advance page

* fix advance page for v6 and v7

* include error message component

* improve side menu

* fix build issue

* update with migration guide

* fix build

* update controller

* include ts page for v6 and v7

* include extension

* fix path

* update handleSubmit API

* include nav animation and text underline

* useController example fix list of imports (#513)

* update nav and api for validate function

* fix watch table

* working on the home page

* update feedback section

* remove perf test

* update content

* title clean up

* improve sub title

* fix font size

* update doc

* update doc

* upate footer

* include the new article

* update with controller

* update on CSB for get started page

* finish getStarted page

* update type circle reference

* complete get started page

* update with unregister

* update formState page

* update watch page with CSB

* update handleSubmit csb

* update handleSubmit CSB

* update reset API csb

* include setError csb

* update clearError csb

* update setValue CSB

* update getValues csb

* update trigger csb

* update control csb

* update controller csb

* update useFormContext csb

* update useWatch

* update error message csb

* update useFieldArray

* update ts csb

* update advance page

* fix clearErrors

* update faq csb

* close #505

* update migration guide

* doc clean up and update rules

* include qiita blog post address

* update info on append/prepend/insert action

* update doc on hook form issue #4333

* update doc on setValue

* minor doc update

* update video

* update react native video

* Fix example code (#520)

* add default api version 7

* Remove unused prop

* Add rel="noreferrer" to anchor tag

* Remove extra closing bracket

* Update to v7 tag documentation for compatibility with devtools (#522)

* Update to v7 tag for compatibility

I ran into an issue using the wrong version with the v7 with v2 of devtools with `typeError: getValues is not a function` via npm tag https://www.npmjs.com/package/@hookform/devtools

* docs: Update text for next tag for devtools to display

* update about us page

* update on setValue

* missing name attribute

* update clearErrors rules

* fix typo

* update on migration guide and useFieldArray doc

* include more infor for useFieldArray

* update resolver blog post

* clean up faq

* minor structure clean up

* fix broken build

* fix build

* include information about useTypedController

* include info for not support flat array

* update v7 module

* update order

* update get started url

* more doc clean up for v7

* more v7 update and clean up

* fix question on FAQ

* update gatsby

* include tip for useController

* fix mobile and tablet view

* include new video in the resource

* update resources page

* include tip section for Controller

* update register rules

* update disabled input with getValues()

* update rules for handleSubmit

* include csb example

* update getstarted page

* remvoe extra space

* fix example on getStarted.ts

* inlcude tips section for useWatch

* improve useController type

* update unique input name about useFieldArray

* include important message

Co-authored-by: Nastya <32715171+NastyaLo@users.noreply.github.com>
Co-authored-by: Rakibul Hasan⚡ <xenax.rakibul@gmail.com>
Co-authored-by: Jack Howard <jackhowaa@gmail.com>