Update:missing colon (#725)
Due to a lack of colons, the following error has been fixed.

```
Failed to compile.

SyntaxError: /Users/program/src/components/pages/SignUp.js: Unexpected token, expected "," (7:17)
   5 | export default function App() {
   6 |   const { register, formState: { errors }, handleSubmit } = useForm({
>  7 |     criteriaMode "all"
     |                  ^
   8 |   });
   9 |   const onSubmit = data => console.log(data);
  10 |
```